language: go
go:
  - 1.11

services:
  - docker

jobs:
  include:
    - stage: test1
      before_install:
        - apt-get update
        - apt-get install -y git
      install:
        - git clone https://github.com/PaulRosset/rehover.git && cd previs
      script: go run ../main.go